In [1]:
import poke_eval_df as ped

df = ped.get_eval_df()

INFO:tensorflow:Creating model
INFO:tensorflow:Loading weights
INFO:tensorflow:Loading model checkpoints/jul1/vector-59999.
INFO:tensorflow:Restoring parameters from checkpoints/jul1/vector-59999
INFO:tensorflow:Loading test set

In [4]:
df.T.sort_values(0)

              0         1         2         3         4         5
49424 -4.509216 -4.332751 -4.517359 -4.250740 -4.273936 -3.436237
27243 -4.022378 -4.108168 -4.161630 -4.049906 -4.082306 -3.441075
22950 -3.975102 -3.715978 -4.053372 -3.884254 -3.847092 -3.519711
47114 -3.695168 -3.772423 -4.228010 -4.138885 -1.612504 -1.985154
30066 -3.586402 -3.656693 -3.789089 -3.799748 -3.895504 -2.700799
33334 -3.301108 -0.952680  0.273033 -1.009184 -1.777301 -2.067649
32423 -2.963467 -3.273592 -3.456727 -3.574793 -3.763761 -2.293863
14233 -2.290169 -2.961495 -0.575858 -1.139337 -1.823675 -2.022932
27086 -1.446610 -0.859659 -0.798758 -0.747142 -0.796595 -0.607264
15598 -1.312759 -1.486603 -1.792294 -1.947317 -2.424414 -2.633214
35951 -1.308456 -0.323437  0.240166  0.266138  0.249154  0.418306
19348 -0.924250 -0.071390  0.483518  0.158395 -0.474221 -0.225722
15429 -0.357890  0.216309  0.325019 -0.111572 -0.665504 -0.507403
27845 -0.323136  0.256806  0.690763  0.683785  0.605721  0.673285

In [5]:
from scipy.special import expit
df.T.sort_values(0).apply(expit)

              0         1         2         3         4         5
49424  0.010887  0.012961  0.010800  0.014053  0.013736  0.031182
27243  0.017595  0.016172  0.015343  0.017126  0.016589  0.031036
22950  0.018431  0.023754  0.017067  0.020149  0.020896  0.028757
47114  0.024241  0.022479  0.014372  0.015691  0.166241  0.120771
30066  0.026951  0.025168  0.022116  0.021887  0.019928  0.062926
33334  0.035533  0.278346  0.567837  0.267140  0.144637  0.112281
32423  0.049104  0.036488  0.030569  0.027257  0.022670  0.091633
14233  0.091940  0.049196  0.359886  0.242442  0.138993  0.116816
27086  0.190524  0.297411  0.310291  0.321444  0.310754  0.352684
15598  0.212026  0.184432  0.142792  0.124846  0.081330  0.067031
35951  0.212745  0.419838  0.559755  0.566145  0.561968  0.603078
19348  0.284093  0.482160  0.618578  0.539516  0.383618  0.443808
15429  0.411470  0.553867  0.580547  0.472136  0.339504  0.375803
27845  0.419912  0.563851  0.666137  0.664583  0.646964  0.662238